apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: "ms-casino-go-v2"
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

patchesJson6902:
  - target:
      group: ""
      version: v1
      kind: ConfigMap
      name: "ms-casino-go-v2-config"
    patch: |-
      - op: add
        path: /data/LOG_LEVEL
        value: "DEBUG"
      - op: add
        path: /data/APP_ENV
        value: "development"
      - op: add
        path: /data/DD_ENABLED
        value: "false"
