apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "ms-casino-go-v2-hpa"
  namespace: "default"
  labels:
    app: "ms-casino-go-v2"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "ms-casino-go-v2"
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
